wso2/aws-is

pattern-1/pattern-1.yaml

> Fixes #1 
> Allowing users to deploy WSO2 Identity Server 5.5.0 Pattern 1 in AWS using CloudFormation.
> JDK - 1.8u144

Adding Cloudformation template for WSO2 Identity Server 5.5.0 pattern 1

---

is-with-analytics/is-with-analytics.yaml

> Update load balancer security groups
> Restricting to a set of limited ports to access the security group

Update security group

---

scalable-is/scalable-is.yaml

> Removing the default Database Username and Password

Remove default DB username and password

---

is-with-analytics/is-with-analytics.yaml
scalable-is/scalable-is.yaml

> Updating Parameter descriptions

Update paramter descriptions

---

is-with-analytics/is-with-analytics.yaml
scalable-is/scalable-is.yaml

> Merging the 5.7.x branch to the master branch

Merging the 5.7.x branch to the master branch

---

scalable-is/scalable-is.yaml

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

generalizing CFN for multiple versions

---

README.md
is-samples/README.md
is-samples/test-is-samples.yml

> Is- Samples cloudformation script

Add is-samples cloud-formation scripts

---

scalable-is/scalable-is.yaml

> Replace ELB with ALB
> Fixes #11 
> Update the CF template to use the latest ALB, since ELBs are deprecated.

Update CF templates to use ALB

---

is-samples/test-is-samples.yml

Enable reusing the same sample deployment for different product versions.
Parameterize the product version and use it

Parameterize the ProductVersion in test-is-samples deployment

---

scalable-is/scalable-is.yaml

> add cfn signal and remove product versions parameter

add cfn signal and remove product versions parameter

---

scalable-is/scalable-is.yaml

> Publish wso2carbon logs to ElasticSearch
> Remove multiAZ in RDS
> Update CFN signal loop condition.

Add Elasticsearch log publishing URL

---

scalable-is/scalable-is.yaml

> Open Hazelcast clustering port 5701 for AWS membership scheme

Open hazelcast port 5701

---

README.md
is-samples/test-is-samples.yml

- Deploy PassiveSTSSampleApp into the tomcat server

Deploy PassiveSTSSampleApp

---

scalable-is/scalable-is.yaml

> Update creation policy timeout to 20mins

Update creation policy timeout

---

Minimum-HA/scalable-is.yaml

> Add centOS option for users to deploy IS 5.7.0
> Add Oracle, SQLServer, Postgres DB options

Add centOS option

---

Minimum-HA/puppet/is570/manifests/init.pp

> Remove Oracle JDK and use AdoptOpenJDK due to licensing issues in Oracle JDK
> JDK - AdoptOpen JDK 8u192b12

Change deployment to use AdoptOpenJDK

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

> Assign public IP address to bastion instance
> Update SQL server parameter description

Assign Public IP address to Bastion Instance

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Update RDS deletion policy from delete to snapshot

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

> Update AMI IDs
> Remove mistakenly added CFN signal

Update AMI IDs

---

puppet/is_analytics_dashboard570/manifests/custom.pp
puppet/is_analytics_dashboard570/manifests/init.pp
puppet/is_analytics_dashboard570/manifests/params.pp
puppet/is_analytics_dashboard570/manifests/startserver.pp
puppet/is_analytics_dashboard570/templates/carbon-home/bin/dashboard.sh.erb
puppet/is_analytics_dashboard570/templates/carbon-home/conf/dashboard/deployment.yaml.erb
puppet/is_analytics_dashboard570/templates/wso2is-analytics-dashboard.service.erb
puppet/is_analytics_worker570/manifests/custom.pp
puppet/is_analytics_worker570/manifests/init.pp
puppet/is_analytics_worker570/manifests/params.pp
puppet/is_analytics_worker570/manifests/startserver.pp
puppet/is_analytics_worker570/templates/carbon-home/bin/worker.sh.erb
puppet/is_analytics_worker570/templates/carbon-home/conf/worker/deployment.yaml.erb
puppet/is_analytics_worker570/templates/wso2is-analytics-worker.service.erb

> Add Puppet modules for IS Analytics Worker and Analytics Dashboard
> Parameterize the IS Analytics Puppet modules
> JDK version - Adopt OpenJDK 8, Amazon Corretto 8
> Operating systems - Ubuntu18.04, CentOS7,
> Databases - Oracle 11/12, MySQL 5.6/5.7, Postgres 9.4/9.6/9.10/ MSSQL SE-13/14

Add Puppet modules for IS Analytics 5.7.0

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml
puppet/is580_master/build.sh
puppet/is_analytics_dashboard580_master/build.sh
puppet/is_analytics_worker580_master/build.sh

> Update AMIs
> Update the build scripts to run inplace update as the default channel
> Add an update scenario handling for inplace update tool

Update AMIs and Puppet build script

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

> Update logstash config files with the latest product path

Update logstash conf files

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

> Clean unwanted config files from the Puppet Agent
> Update Puppet agent AMIs

Update Puppet Agent AMIs

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

> Fix debian running in interactive mode after new update.

Run debian as non interactive mode

---

Minimum-HA/scalable-is.yaml

> Update puppet modules
> Disable analytics for scalable-is

Update puppet modules

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

> Add CFn templates for Identity Server 5.9.0
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Update CFN templates for IS 5.9.0

---

Minimum-HA/scalable-is.yaml

> Update AMIs for the pupetmaster instances

Update Puppetmaster AMIs

---

is-with-analytics/is-with-analytics.yaml

> Update MySQL 5.7.0 DB scripts
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Update MySQL 5.7.0 DB scripts

---

is-with-analytics/is-with-analytics.yaml

Fix issue with WSO2ISAnalyticsLoadBalancer configs
Fix issue with WSO2ISAnalyticsLoadBalancer configs

Fix issue with WSO2ISAnalyticsLoadBalancer configs

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml
puppet/is590/manifests/custom.pp
puppet/is590/manifests/init.pp
puppet/is590/manifests/params.pp
puppet/is590/manifests/startserver.pp
puppet/is590/templates/carbon-home/bin/wso2server.sh.erb
puppet/is590/templates/carbon-home/repository/conf/deployment.toml.erb
puppet/is_analytics_dashboard/manifests/custom.pp
puppet/is_analytics_dashboard/manifests/init.pp
puppet/is_analytics_dashboard/manifests/params.pp
puppet/is_analytics_dashboard/manifests/startserver.pp
puppet/is_analytics_dashboard/templates/carbon-home/bin/dashboard.sh.erb
puppet/is_analytics_dashboard/templates/carbon-home/conf/dashboard/deployment.yaml.erb
puppet/is_analytics_dashboard/templates/wso2is-analytics-dashboard.service.erb
puppet/is_analytics_worker/manifests/custom.pp
puppet/is_analytics_worker/manifests/init.pp
puppet/is_analytics_worker/manifests/params.pp
puppet/is_analytics_worker/manifests/startserver.pp
puppet/is_analytics_worker/templates/carbon-home/bin/worker.sh.erb
puppet/is_analytics_worker/templates/carbon-home/conf/worker/deployment.yaml.erb
puppet/is_analytics_worker/templates/wso2is-analytics-worker.service.erb

Update master with 5.9.x changes
Update master with 5.9.x changes

Update master with 5.9.x changes

---

is-with-analytics/is-with-analytics.yaml

Revert #58  
Undo errornoeos configurations.

Revert changes of PR #58

---

is-with-analytics/is-with-analytics.yaml

Update master with 5.9.x changes
Update master with 5.9.x changes

Merge 5.9.x to master

---

Minimum-HA/scalable-is.yaml

Fix consent DB issue
Fix consent DB issue
AWS

Fix the consent DB issue

---

Minimum-HA/scalable-is.yaml

Merge 5.9.x to master branch
https://github.com/wso2/aws-is/pull/67

Fix cluster deployment proxy port issue in 5.9.x and merge to master

---

Minimum-HA/scalable-is.yaml

Add WSL to the AMI
Add WSL to the AMI
AWS

Add WSL to the AMI

---

Minimum-HA/scalable-is.yaml

PDF generation failed due to an error in the wso2-init.sh script. Fixed that and created a new AMI.
Fix in-place updates tool - PDF issue
AWS

Fix in-place updates tool - PDF issue

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

Get updated wso2-init.sh from the s3 bucket.
Get updated wso2-init.sh from the s3 bucket.
AWS

Modify wso2-init.sh

---

Minimum-HA/scalable-is.yaml
is-with-analytics/is-with-analytics.yaml

Fix wget command

---

Minimum-HA/scalable-is.yaml

Fix the issue related to getting updates.
Fix the issue related to getting updates.
AWS

Fix WUM issue

---

Minimum-HA/scalable-is.yaml

Merge 5.10.x to master
Merge 5.10.x to master

Merge 5.10.x to master

---

network-configs/network.yaml

Add CFN for network configs

---

db-configs/database.yaml

Add DB Endpoint and Port to outputs
AWS

Add DB Endpoint and Port to outputs

---

database/README.md
network/README.md
product/README.md
product/identity.yaml

Modify README files with better content

Modify README files with better content

---

Minimum-HA/nested-identity.yaml
network/network.yaml
product/identity.yaml

Add nested CloudFormation script
AWS

Add nested CloudFormation script

---

README.md
database/README.md
network/README.md
product/README.md

Add product config details
Partially fixes #79

Add product config details

---

Minimum-HA/nested-identity-minimal.yaml

Add CFN with minimum configs
AWS

Add CFN with minimum configs

---

database/README.md
product/README.md

Fix URLs in Readme files
Fix #93

Fix URLs in Readme files

---

README.md
database/README.md
network/README.md
product/README.md

Update README files with the review comments

Update README files

---

Minimum-HA/nested-identity.yaml
database/database.yaml
product/identity.yaml

Add Environment to DB and product configs
Partially fixes #79

Add Environment to DB and product configs

---

network/network.yaml

Add Environment as a proper tag for VPC

---

Minimum-HA/nested-identity-minimal.yaml
Minimum-HA/nested-identity.yaml
product/identity.yaml

> Update CloudFormation Scripts for IS-5.11.0

Update CloudFormation Scripts for IS-5.11.0 
